config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

  devise_scope :user do
    get "admin/login" => "devise/sessions#new"
    delete "admin/logout" => "devise/sessions#destroy"
  end

  root "home#index"
  
  namespace :admin do
    resources :wines
    resources :tasting_packages
    resources :events, only: [:index, :show]
  end

  post "user_service/create" => "user_service#create"
  get "guests/rsvp/:invite_key" => "guests#rsvp", as: "register_rsvp"
  put "guests/update" => "guests#update"

  resources :scores, only: [:index, :create, :new] do
    collection do
      get :final
    end
  end

  namespace :events do
    resources :sessions, only: [:new, :create] do
      collection do
        delete :destroy
      end
    end
  end

  resources :events do
    member do
      post :send_reminder
    end
  end
  
  put "events/:id/:operation" , to: "events#control", as: "event_control"

end

app/models/tasting_package.rb
class TastingPackage < ActiveRecord::Base
  has_many :wine_packages, class_name: "WinePackage"
  has_many :wines, through: :wine_packages, dependent: :destroy

  TASTING_CODES = ("A".."Z").to_a

  def add_wines(wine_ids, custom_tasting_codes=[])
    self.wines.clear #clear to ensure no bad data
    wine_ids.uniq.each_with_index do |wine_id, index|
      begin
        wine = Wine.find(wine_id)
        wine_package = WinePackage.new
        wine_package.wine_id = wine.id
        wine_package.tasting_package_id = self.id
        wine_package.wine_tasting_code = custom_tasting_codes[index] || TASTING_CODES[index]
        wine_package.save!
      rescue
        next
      end
    end
  end

  def wine_selections
    wines.collect {|wine| [wine.name, wine.id]}
  end

end

app/controllers/admin/tasting_packages_controller.rb
module Admin
  class TastingPackagesController < ApplicationController
    
    before_filter :authenticate_user!
    before_filter :check_admin_status

    def index
      @packages = TastingPackage.includes(:wines)
    end

    def new
      @package = TastingPackage.new
    end

    def create
      if params[:wine_selection].present?
        @package = TastingPackage.create(tasting_package_params)
        @package.add_wines(params[:wine_selection], params.fetch(:wine_tasting_codes, []))
      else
        flash[:error] = "Tasting packages cannot be created without a wine list."
      end
      redirect_to admin_tasting_packages_url
    end

    def show
      @package = TastingPackage.find(params[:id])
      @wine_list = WinePackage.wine_list(@package.id)
    rescue
      flash[:error] = "The package could not be found"
      redirect_to admin_tasting_packages_url
    end

    def edit
      @package = TastingPackage.includes(:wines).where(id: params[:id]).first
      raise ActiveRecord::RecordNotFound if @package.nil?
      @wine_list = WinePackage.wine_list(@package.id)
    rescue
      flash[:error] = "The package could not be found"
      redirect_to admin_tasting_packages_url
    end

    def update
      if params[:wine_selection].present?
        wine_tasting_codes = params.fetch(:wine_tasting_codes, []).reject {|el| el.empty?}
        @package = TastingPackage.find(params[:id])
        @package.update_attributes(tasting_package_params)
        @package.add_wines(params[:wine_selection], wine_tasting_codes)
      else
        flash[:error] = "Tasting packages cannot be updated without a wine list."
      end
      redirect_to admin_tasting_packages_url
    end

    def destroy
      @package = TastingPackage.find(params[:id])
      @package.destroy
    rescue
      flash[:error] = "The package could not be found"
      redirect_to admin_tasting_packages_url
    end

    private
    def tasting_package_params
      params[:tasting_package].permit(:name, :price)
    end

  end
end

app/views/admin/tasting_packages/edit.html.slim
.custom-page-header
  h4 Edit tasting package

= form_for(@package, url: admin_tasting_package_url(@package.id), method: :put, html: {class: "form-horizontal"}) do |f|
  
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control", required: true

  .form-group
    = f.label :price, class: "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :price, value: number_with_precision(f.object.price, precision: 2) , class: "form-control", required: true, step: 0.01

  - if @wine_list.empty?
    #package-wine-fields.form-group
      = label_tag "Add Wines", nil, class: "col-sm-2 control-label"
      .col-sm-10.wine-controls
        .wine-entry
          .row
            .col-xs-5.col-sm-5
              = select_tag "wine_selection[]", options_for_select(Wine.wine_selections), class: "form-control"
            .col-xs-2.col-sm-2
              = label_tag "Wine code", nil, class: "control-label"
            .col-xs-3.col-sm-3
              = text_field_tag "wine_tasting_codes[]", nil, class: "form-control wine-code-holder", placeholder: "Enter wine code. eg. A"
            .col-xs-2.col-sm-2
              = link_to "#", class: "btn btn-default package-wine-add-btn" do
                i.fa.fa-plus

  - else
    - if @wine_list.size == 1
      #package-wine-fields.form-group
        = label_tag "Edit Wines", nil, class: "col-sm-2 control-label"
        .col-sm-10.wine-controls
          .wine-entry
            .row
              .col-xs-5.col-sm-5
                = select_tag "wine_selection[]", options_for_select(Wine.wine_selections, @wine_list.first.id), class: "form-control"
              .col-xs-2.col-sm-2
                = label_tag "Wine code", nil, class: "control-label"
              .col-xs-3.col-sm-3
                = text_field_tag "wine_tasting_codes[]", @wine_list.first.wine_tasting_code, class: "form-control wine-code-holder", placeholder: "Enter wine code. eg. A"
              .col-xs-2.col-sm-2
                = link_to "#", class: "btn btn-default package-wine-add-btn" do
                  i.fa.fa-plus
    - else
      #package-wine-fields.form-group
        = label_tag "Edit Wines", nil, class: "col-sm-2 control-label"
        .col-sm-10.wine-controls
          - @wine_list[0..-2].each do |wine|
            .wine-entry
              .row
                .col-xs-5.col-sm-5
                  = select_tag "wine_selection[]", options_for_select(Wine.wine_selections, wine.id), class: "form-control"
                .col-xs-2.col-sm-2
                  = label_tag "Wine code", nil, class: "control-label"
                .col-xs-3.col-sm-3
                  = text_field_tag "wine_tasting_codes[]", wine.wine_tasting_code, class: "form-control wine-code-holder",placeholder: "Enter wine code. eg. A"
                .col-xs-2.col-sm-2
                  = link_to "#", class: "btn btn-danger package-wine-remove-btn" do
                    i.fa.fa-minus
          .wine-entry
            .row
              .col-xs-5.col-sm-5
                = select_tag "wine_selection[]", options_for_select(Wine.wine_selections, @wine_list.last.id), class: "form-control"
              .col-xs-2.col-sm-2
                = label_tag "Wine code", nil, class: "control-label"
              .col-xs-3.col-sm-3
                = text_field_tag "wine_tasting_codes[]", @wine_list.last.wine_tasting_code, class: "form-control wine-code-holder",placeholder: "Enter wine code. eg. A"
              .col-xs-2.col-sm-2
                = link_to "#", class: "btn btn-default package-wine-add-btn" do
                  i.fa.fa-plus

  .form-group
    .col-md-offset-2.col-md-2
      = f.submit "Save changes", class: "btn btn-primary"
    .col-md-1
      = link_to "Cancel", admin_tasting_packages_url, class: "btn btn-default"

app/views/admin/tasting_packages/index.html.slim
.wine-header
  .row
    .col-md-4.col-xs-4
      strong Tasting Packages
    .col-md-4.col-md-offset-4.col-xs-4.col-xs-offset-4.add-wine-btn
      = link_to new_admin_tasting_package_url, class: "btn btn-default" do
        i.fa.fa-plus
        | Add
- if @packages.empty?
 span No tasting packages. Use the Add button to create packages.

- else
  .table-container
    table.table.sortable
      thead
        tr
          th Name
          th Price

      tbody
        - @packages.each do |package|
          tr
            td 
              = link_to "#{package.name}", admin_tasting_package_url(package.id)
            #{package.name}
            td #{number_to_currency(package.price)}
            td
              = link_to edit_admin_tasting_package_url(package.id), class: "btn btn-default" do
                i.fa.fa-pencil
                | Edit
            td
              = link_to admin_tasting_package_url(package.id), method: :delete, class: "btn btn-danger" do
                i.fa.fa-trash
                | Delete

app/views/admin/tasting_packages/new.html.slim
.custom-page-header
  h4 Create a tasting package

= form_for(@package, as: :tasting_package, url: admin_tasting_packages_url, html: {class: "form-horizontal"}) do |f|
  
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control", required: true

  .form-group
    = f.label :price, class: "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :price, class: "form-control", required: true, step: "any"

  #package-wine-fields.form-group
    = label_tag "Add Wines", nil, class: "col-sm-2 control-label"
    .col-sm-10.wine-controls
      .wine-entry
        .row
          .col-xs-5.col-sm-5
            = select_tag "wine_selection[]", options_for_select(Wine.wine_selections), class: "form-control"
          .col-xs-2.col-sm-2
            = label_tag "Wine code", nil, class: "control-label"
          .col-xs-3.col-sm-3
            = text_field_tag "wine_tasting_codes[]", nil, class: "form-control wine-code-holder", placeholder: "Enter wine code. eg. A"
          .col-xs-2.col-sm-2
            = link_to "#", class: "btn btn-default package-wine-add-btn" do
              i.fa.fa-plus

  .form-group
    .col-md-offset-2.col-md-2
      = f.submit "Create package", class: "btn btn-primary"
    .col-md-1
      = link_to "Cancel", admin_tasting_packages_url, class: "btn btn-default"

app/views/admin/tasting_packages/show.html.slim
.custom-page-header
  .row
    .col-md-4.col-xs-4
      strong Tasting Package #{@package.id}
    .col-md-4.col-md-offset-4.col-xs-4.col-xs-offset-4
      = link_to edit_admin_tasting_package_url(@package.id), class: "btn btn-default" do
        i.fa.fa-pencil
        | Edit

  .package-details
    .row
      .col-sm-2.col-sm-offset-2
        strong Name
      .col-sm-6
        span #{@package.name}

    .row
      .col-sm-2.col-sm-offset-2
        strong Price
      .col-sm-6
        span #{number_to_currency(@package.price)}

    - if !@wine_list.empty?
      .row
        .col-sm-2.col-sm-offset-2
          strong Wines
        .col-sm-6
          span #{@wine_list.first.try(:name)}

      - @wine_list[1..-1].each do |wine|
        .row
          .col-sm-2.col-sm-offset-2
          .col-sm-6
            span #{wine.name}
      