config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

  devise_scope :user do
    get "admin/login" => "devise/sessions#new"
    delete "admin/logout" => "devise/sessions#destroy"
  end

  root "home#index"
  
  namespace :admin do
    resources :wines
    resources :tasting_packages
    resources :events, only: [:index, :show]
  end

  post "user_service/create" => "user_service#create"
  get "guests/rsvp/:invite_key" => "guests#rsvp", as: "register_rsvp"
  put "guests/update" => "guests#update"

  resources :scores, only: [:index, :create, :new] do
    collection do
      get :final
    end
  end

  namespace :events do
    resources :sessions, only: [:new, :create] do
      collection do
        delete :destroy
      end
    end
  end

  resources :events do
    member do
      post :send_reminder
    end
  end
  
  put "events/:id/:operation" , to: "events#control", as: "event_control"

end

app/models/event.rb
class Event < ActiveRecord::Base
  include AASM

  belongs_to :host, foreign_key: :host_user_id, class_name: "User"
  belongs_to :tasting_package
  has_many :guests, dependent: :destroy
  has_many :scorecards

  before_create :generate_event_key
  after_create :send_email_notification

  scope :hosted_by, ->(user_id) {where("host_user_id = ?", user_id)}

  aasm column: :state do
    state :unstarted, initial: true
    state :started
    state :completed

    event :start_event do
      transitions to: :started, from: [:unstarted]
    end

    event :finish_event do
      transitions to: :completed, from: [:started]
    end
  end

  def final_scores
    Scorecard.where(event_id: self.id)
             .joins(:wine)
             .select("sum(rank) as wine_rank, wine_id, wines.name as wine_name")
             .group(:wine_id)
             .order("wine_rank")
  end

  def current_guest_rankings(user_id)
    score_cards = Scorecard.where(event_id: self.id, user_id: user_id)
                           .joins(:wine)
                           .select("sum(rank) as wine_rank, wine_id, wines.name as wine_name")
                           .group(:wine_id)
                           .order("wine_rank")

    result = []
    score_cards.each do |card|
      result << WinePackage.where(tasting_package_id: self.tasting_package.id, wine_id: card.wine_id).first.try(:wine_tasting_code)
    end
    result
  end

  def send_reminders
    guests.each {|guest| guest.send_reminder}
  end

  def parse_event_time
    self[:event_time].strftime("%I:%M %p") if self[:event_time]
  end

  def parse_event_date
    self[:event_date].strftime('%m/%d/%Y') if self[:event_date]
  end

  def event_date=(value)
    self[:event_date] = Date.strptime(value, '%m/%d/%Y')
  end

  private
  def generate_event_key
    self[:event_key] = rand(36**8).to_s(36)
  end

  def send_email_notification
    ApplicationMailer.new_event_notification(self).deliver_later
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < ApplicationController
    before_filter :authenticate_user!
    before_filter :check_admin_status

    def index
      @events = Event.includes(:host, :tasting_package)
    end

    def show
      @event = Event.find(params[:id])
    rescue
      flash[:error] = "The event could not be found"
      redirect_to admin_events_url
    end

  end
end

app/controllers/events/sessions_controller.rb
module Events
  class SessionsController < ApplicationController

    def new
      session[:guest_id] = nil
    end

    def create
      guest = authenticate_guest(params[:email], params[:event_key])
      if guest
        session[:guest_id] = guest.id
        session[:event_key] = params[:event_key]
        redirect_to events_url
      else
        flash[:error] = "It looks like you haven't been invited for the event. Please contact the event's host for more details."
        redirect_to new_events_session_url
      end
    end

    def destroy
      session[:guest_id] = nil
      redirect_to new_events_session_url
    end

  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :require_guest, only: [:index, :show, :edit, :update, :control]

  def new
    @event = Event.new
    @tasting_package_id = params[:tasting_package_id]
    @tasting_package = TastingPackage.find(@tasting_package_id)
    @host_user_id = params[:host_user_id]
  end

  def index
    @events = Event.hosted_by(current_guest.id)
  end

  def create
    event = Event.create(event_params)
    Guest.process_invites(params[:invite_emails].split(", "), event) if event
    flash[:success] = "Thank you! Your FlowTasting event has been created, and your guests have been invited. We sent you an email with your Event key. Use it to manage your event and run the Virtual Tasting Room during your tasting."
    redirect_to event_url(event.id)
  end

  #TODO: Need to show event only if created by current user
  def show
    @event = Event.find(params[:id])
  end

  def send_reminder
    event = Event.find(params[:id])
    event.send_reminders
    flash[:success] = "Reminders have been sent to your guests."
    redirect_to event_url(event.id)
  end

  def edit
    event = Event.where(id: params[:id]).includes(guests: :user)
    if current_guest == event.first.host
      @event = event.first
      @invite_emails = []
      event.each do |event_obj|
        event_obj.guests.each {|guest| @invite_emails << guest.user.email }
      end
      @invite_emails = @invite_emails.join(",")
    else
      flash[:error] = "You are not hosting the event and don't have permission to edit"
      redirect_to events_url
    end
    
  end

  def update
    event = Event.find(params[:id])
    event.update_attributes(event_params)
    Guest.process_invites(params[:invite_emails].split(", "), event) if params[:invite_emails].present?
    flash[:success] = "Your FlowTasting event has been updated."
    redirect_to event_url(params[:id])
  end

  def control
    event = Event.find(params[:id])
    if params[:operation] == "start"
      event.start_event!
    elsif params[:operation] == "finish"
      event.finish_event!
    end
    redirect_to scores_url
  end

  private
  def event_params
    params[:event].permit(:name, :description, :event_date, :event_time, :venue, :tasting_package_id, :host_user_id)
  end
end

app/views/events/edit.html.slim
.custom-page-header
  h4 Edit your FlowTasting event

= form_for(@event, url: event_url(@event.id), method: :put, html: {class: "form-horizontal"}) do |f|
  
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control", required: true

  .form-group
    = f.label :description, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :description, value: (f.object.description.blank? ? "Join us for a #{@tasting_package.try(:name).try(:titleize)} wine tasting party. We’ll blind taste 6 themed wines, and rate and share our favorites. Please plan to bring 6 glasses." : f.object.description ) , class: "form-control", required: true

  .form-group
    = f.label "Date", class: "col-sm-2 control-label"
    .col-sm-10
      .input-group.date
        = f.text_field :event_date, value: f.object.parse_event_date, class: "form-control", id: "event_date_picker", required: true, placeholder: "Event date"
        span.input-group-addon
          .event-date-icon
            span.glyphicon.glyphicon-calendar


  .form-group
    = f.label "Time", class: "col-sm-2 control-label"
    .col-sm-10
      .input-group.date
        = f.text_field :event_time, value: f.object.parse_event_time,class: "form-control", id: "event_time_picker", required: true, placeholder: "Event time"
        span.input-group-addon
          .event-time-icon
            span.glyphicon.glyphicon-time

  .form-group
    = f.label :place, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :venue, class: "form-control", required: true

  .form-group
    = label_tag :invite_guests, "Invite guests", class: "col-sm-2 control-label"
    .col-sm-10
      = text_field_tag :invite_emails, @invite_emails, class: "form-control invite-emails-field", placeholder: "Type email and press enter. eg wilma@gmail.com"

  .form-group
    .col-md-offset-2.col-md-2
      = f.submit "Update event", class: "btn btn-primary"
    .col-md-1
      = link_to "Cancel", events_url, class: "btn btn-default"

app/views/events/index.html.slim
.wine-header
  .row
    .col-md-4.col-xs-4
      strong Events

- if @events.empty?
  span No events found.

- else
  .table-container
    table.table
      thead
        tr
          th Name
          th Event key
          th

      tbody
        - @events.each do |event|
          tr class="#{(event.host == current_guest && event == current_event) ? "highlight-current-event" : nil}"
            td
              = link_to "#{event.name}", event_url(event.id)
            #{event.name}
            td #{event.event_key}
            td
              = link_to edit_event_url(event.id), class: "btn btn-default" do
                i.fa.fa-pencil
                | Edit

app/views/events/new.html.slim
.custom-page-header
  h4 Create your FlowTasting event
- if @tasting_package_id.nil? || @host_user_id.nil?
  strong Required parameters are missing. Event cannot be created.
- else
  = form_for(@event, as: :event, url: events_path, html: {class: "form-horizontal"}) do |f|
    
    .form-group
      = f.label :name, class: "col-sm-2 control-label"
      .col-sm-10
        = f.text_field :name, class: "form-control", required: true

    .form-group
      = f.label "description (email body)", class: "col-sm-2 control-label"
      .col-sm-10
        = f.text_area :description, value: "Join us for a #{@tasting_package.try(:name).try(:titleize)} wine tasting party. We’ll blind taste 6 themed wines, and rate and share our favorites. Please plan to bring 6 glasses.", class: "form-control", required: true

    .form-group
      = f.label "Date", class: "col-sm-2 control-label"
      .col-sm-10
        .input-group.date
          = f.text_field :event_date, class: "form-control", id: "event_date_picker", required: true, placeholder: "Event date"
          span.input-group-addon
            .event-date-icon
              span.glyphicon.glyphicon-calendar

    .form-group
      = f.label "Time", class: "col-sm-2 control-label"
      .col-sm-10
        .input-group.date
          = f.text_field :event_time, class: "form-control", id: "event_time_picker", required: true, placeholder: "Event time"
          span.input-group-addon
            .event-time-icon
              span.glyphicon.glyphicon-time

    .form-group
      = f.label :place, class: "col-sm-2 control-label"
      .col-sm-10
        = f.text_field :venue, class: "form-control", required: true

    .form-group
      = label_tag :invite_guests, "Invite guests", class: "col-sm-2 control-label"
      .col-sm-10
        = text_field_tag :invite_emails, nil, class: "form-control invite-emails-field", placeholder: "Type email and press enter. eg wilma@gmail.com"

    = f.hidden_field :tasting_package_id, value: @tasting_package_id
    = f.hidden_field :host_user_id, value: @host_user_id

    .form-group
      .col-md-offset-2.col-md-2
        = f.submit "Create event", class: "btn btn-primary"
      .col-md-1
        = link_to "Cancel", admin_wines_url, class: "btn btn-default"

app/views/events/show.html.slim
.custom-page-header
  .row
    .col-md-2.col-xs-2
      strong Event details
    .col-md-10.col-xs-10
      span.pull-right.left-15
        = link_to edit_event_url(@event.id), class: "btn btn-default" do
          i.fa.fa-pencil
          | Edit
      span.pull-right
        = link_to send_reminder_event_url(@event.id), method: :post, class: "btn btn-default" do
          i.fa.fa-envelope
          | Remind guests

  .package-details.top-20
    .row.top-5
      .col-xs-5.col-sm-2.col-sm-offset-2.col-xs-offset-2
        strong FlowTasting Event
      .col-sm-4.col.xs-7
        span #{@event.name}

    .row.top-5
      .col-xs-5.col-sm-2.col-sm-offset-2.col-xs-offset-2
        strong Event key
      .col-sm-4.col.xs-7
        span #{@event.event_key}

    .row.top-5
      .col-xs-5.col-sm-2.col-sm-offset-2.col-xs-offset-2
        strong Description
      .col-sm-4.col.xs-7
        span #{@event.description}

    .row.top-5
      .col-xs-5.col-sm-2.col-sm-offset-2.col-xs-offset-2
        strong Date
      .col-sm-4.col.xs-7
        span #{@event.parse_event_date}

    .row.top-5
      .col-xs-5.col-sm-2.col-sm-offset-2.col-xs-offset-2
        strong Time
      .col-sm-4.col.xs-7
        span #{@event.parse_event_time}

    .row.top-5
      .col-xs-5.col-sm-2.col-sm-offset-2.col-xs-offset-2
        strong Place
      .col-sm-4.col.xs-7
        span #{@event.venue}

    - if !@event.guests.empty?
      .row.top-5
        .col-xs-5.col-sm-2.col-sm-offset-2.col-xs-offset-2
          strong Guests
      .row.top-10
        .col-sm-offset-2.col-sm-6.col-xs-8.col-xs-offset-2
          table.table
            thead
              tr
              th Email
              th RSVP

            tbody
              - @event.guests.each do |guest|
                tr
                  td #{guest.user.email}
                  td #{guest.format_rsvp_state}