config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

  devise_scope :user do
    get "admin/login" => "devise/sessions#new"
    delete "admin/logout" => "devise/sessions#destroy"
  end

  root "home#index"
  
  namespace :admin do
    resources :wines
    resources :tasting_packages
    resources :events, only: [:index, :show]
  end

  post "user_service/create" => "user_service#create"
  get "guests/rsvp/:invite_key" => "guests#rsvp", as: "register_rsvp"
  put "guests/update" => "guests#update"

  resources :scores, only: [:index, :create, :new] do
    collection do
      get :final
    end
  end

  namespace :events do
    resources :sessions, only: [:new, :create] do
      collection do
        delete :destroy
      end
    end
  end

  resources :events do
    member do
      post :send_reminder
    end
  end
  
  put "events/:id/:operation" , to: "events#control", as: "event_control"

end

app/models/wine.rb
class Wine < ActiveRecord::Base

  has_many :wine_packages, class_name: "WinePackage"
  has_many :tasting_packages, through: :wine_packages

  validates_presence_of :name


  def self.wine_selections
    Wine.all.collect {|wine| [wine.name, wine.id]}.sort {|wine_a, wine_b| wine_a.first <=> wine_b.first}
  end

  def vintage=(value)
    self[:vintage] = value.to_i
  end

end

app/controllers/admin/wines_controller.rb
module Admin
  class WinesController < ApplicationController

    before_filter :authenticate_user!
    before_filter :check_admin_status

    def index
      @wines = Wine.all
    end

    def new
      @wine = Wine.new
    end

    def create
      Wine.create(wine_params)
      redirect_to admin_wines_url
    end

    def edit
      @wine = Wine.find(params[:id])
    end

    def update
      @wine = Wine.find(params[:id])
      @wine.update_attributes(wine_params)
      redirect_to admin_wines_url
    end

    def destroy
      @wine = Wine.find(params[:id])
      @wine.destroy
      redirect_to admin_wines_url
    end

    private
    def wine_params
      params[:wine].permit(:name, :region, :wine_type, :description, :fun_facts, :price, :producer, :vintage)
    end
  end
end

app/views/admin/wines/edit.html.slim
.custom-page-header
  h4 Edit wine

= form_for(@wine, url: admin_wine_url(@wine.id), method: :put, html: {class: "form-horizontal"}) do |f|
  
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control", required: true

  .form-group
    = f.label :price, class: "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :price, value: number_with_precision(f.object.price, precision: 2) , class: "form-control", required: true, step: 0.01

  .form-group
    = f.label :region, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :region, class: "form-control", required: true

  .form-group
    = f.label :wine_type, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :wine_type, class: "form-control", required: true

  .form-group
    = f.label :description, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :description, class: "form-control"

  .form-group
    = f.label :fun_facts, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :fun_facts, class: "form-control"

  .form-group
    = f.label :producer, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :producer, class: "form-control"

  .form-group
    = f.label :vintage, class: "col-sm-2 control-label"
    .col-sm-10
      = select_year(f.object.vintage, {start_year: Date.today.year, end_year: 1900}, class: "form-control", name: "wine[vintage]")

  .form-group.edit-wine
    .col-md-offset-2.col-md-2
      = f.submit "Save changes", class: "btn btn-primary"
    .col-md-1
      = link_to "Cancel", admin_wines_url, class: "btn btn-default"

app/views/admin/wines/index.html.slim
.wine-header
  .row
    .col-md-4.col-xs-4
      strong Wine Catalog
    .col-md-4.col-md-offset-4.col-xs-4.col-xs-offset-4.add-wine-btn
      = link_to new_admin_wine_url, class: "btn btn-default" do
        i.fa.fa-plus
        | Add

- if @wines.empty?
  span No wines found. Use the Add button to start building your catalog.

- else
  .table-container
    table.table.sortable
      thead
        tr
          th Name
          th Price
          th Region
          th Type
          th Producer
          th Vintage

      tbody
        - @wines.each do |wine|
          tr
            td #{wine.name}
            td #{number_to_currency(wine.price)}
            td #{wine.region}
            td #{wine.wine_type}
            td #{wine.producer}
            td #{wine.vintage}
            td
              = link_to edit_admin_wine_path(wine.id), class: "btn btn-default" do
                i.fa.fa-pencil
                | Edit
            td
              = link_to admin_wine_url(wine.id), method: :delete, class: "btn btn-danger" do
                i.fa.fa-trash
                | Delete

app/views/admin/wines/new.html.slim
.custom-page-header
  h4 Add a new wine

= form_for(@wine, as: :wine, url: admin_wines_path, html: {class: "form-horizontal"}) do |f|
  
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control", required: true

  .form-group
    = f.label :region, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :region, class: "form-control", required: true

  .form-group
    = f.label :wine_type, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :wine_type, class: "form-control", required: true

  .form-group
    = f.label :price, class: "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :price, class: "form-control", required: true, step: "any"

  .form-group
    = f.label :description, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :description, class: "form-control"

  .form-group
    = f.label :fun_facts, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :fun_facts, class: "form-control"

  .form-group
    = f.label :producer, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :producer, class: "form-control"

  .form-group
    = f.label :vintage, class: "col-sm-2 control-label"
    .col-sm-10
      = select_year(Date.today.year, {start_year: Date.today.year, end_year: 1900}, class: "form-control", name: "wine[vintage]")

  .form-group.add-wine
    .col-md-offset-2.col-md-2
      = f.submit "Add wine", class: "btn btn-primary"
    .col-md-1
      = link_to "Cancel", admin_wines_url, class: "btn btn-default"