config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

  devise_scope :user do
    get "admin/login" => "devise/sessions#new"
    delete "admin/logout" => "devise/sessions#destroy"
  end

  root "home#index"
  
  namespace :admin do
    resources :wines
    resources :tasting_packages
    resources :events, only: [:index, :show]
  end

  post "user_service/create" => "user_service#create"
  get "guests/rsvp/:invite_key" => "guests#rsvp", as: "register_rsvp"
  put "guests/update" => "guests#update"

  resources :scores, only: [:index, :create, :new] do
    collection do
      get :final
    end
  end

  namespace :events do
    resources :sessions, only: [:new, :create] do
      collection do
        delete :destroy
      end
    end
  end

  resources :events do
    member do
      post :send_reminder
    end
  end
  
  put "events/:id/:operation" , to: "events#control", as: "event_control"

end

app/views/layouts/_admin_navbar.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#"Flow tasting

    div#navbar.navbar-collapse.collapse
      ul.nav.navbar-nav
        li class="#{controller_name.include?("wine") ? "active" : nil}"
          = link_to "Wines", admin_wines_url
        li class="#{controller_name.include?("tasting_package") ? "active" : nil}"
          = link_to "Tasting Packages", admin_tasting_packages_url
        li class="#{controller_name.include?("event") ? "active" : nil}"
          = link_to "Events", admin_events_url

      - if current_user
        ul.nav.navbar-nav.navbar-right
          li 
            a href="#" #{current_user.first_name}
          li = link_to "Log out", "/admin/logout", method: :delete
      - else
        ul.nav.navbar-nav.navbar-right
          li
            = link_to "Admin login", "/admin/login"

app/views/layouts/_event_navbar.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#"Flow tasting

    div#navbar.navbar-collapse.collapse

      ul.nav.navbar-nav
        li class="#{controller_name.include?("event") ? "active" : nil}"
          = link_to "My events", events_url
        li class="#{controller_name.include?("score") ? "active" : nil}"
          = link_to "Virtual Tasting Room", scores_url
        li
          a href="mailto:support@flowtasting.com" Support

      - if current_guest
        ul.nav.navbar-nav.navbar-right
          li 
            a href="#" #{current_guest.email}
          li = link_to "Close event", events_sessions_url, method: :delete
      - else
        ul.nav.navbar-nav.navbar-right
          li
            = link_to "Event Login", new_events_session_url

app/views/layouts/_guest_navbar.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#"Flow tasting

    div#navbar.navbar-collapse.collapse
      ul.nav.navbar-nav
        li class="#{controller_name.include?("score") ? "active" : nil}"
          = link_to "Scores", scores_url

      - if current_guest
        ul.nav.navbar-nav.navbar-right
          li 
            a href="#" #{current_guest.user.email}
          li = link_to "Close event", events_sessions_url, method: :delete
      - else
        ul.nav.navbar-nav.navbar-right
          li
            = link_to "Log in", new_events_session_url

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#"Flow tasting

    div#navbar.navbar-collapse.collapse
      ul.nav.navbar-nav
        li.active
          = link_to "Home", root_url
        li
          a href="mailto:support@flowtasting.com" Support

      - if current_user
        ul.nav.navbar-nav.navbar-right
          li 
            a href="#" #{current_user.first_name}
          li = link_to "Log out", "/admin/logout", method: :delete
      - else
        ul.nav.navbar-nav.navbar-right
          li
            = link_to "Admin login", "/admin/login"

app/views/layouts/application.html.slim
doctype strict
html
  head
    title Flow Tasting
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    - if FlowTasting::Application.assets.find_asset("#{controller_name}_controller")
      = javascript_include_tag "#{controller_name}_controller.js", "data-turbolinks-track" => true
    = csrf_meta_tags

    body
      - if controller_path.include?("admin")
        == render partial: "/layouts/admin_navbar"
      - elsif %w[events events/sessions scores guests].include?(controller_path)
        == render partial: "/layouts/event_navbar"
      - else
        == render partial: "/layouts/navbar"
      .container
        == flash_messages
        == yield